export const IPO_Data = [
  {
    id: "go_air",
    full_name: "Go Air Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://cdn.brandfetch.io/goair.in/fallback/transparent/theme/dark/h/512/w/512/icon?t=1720898897333",
    company: "GO AIR",
    date: "4th - 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvest: "₹50,000",
    quantity: "100 Shares/5 Lots",
  },
  {
    id: "bajaj_energy",
    full_name: "Bajaj Enery Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://storage.googleapis.com/gw-prod-asset-netstorage/stocks-ipo/logos/logos_bajajelec-41.png",
    company: "BAJAJ ENERGY",
    date: "4th - 7th Oct 2022",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvest: "₹50,000",
    quantity: "100 Shares/5 Lots",
  },
  {
    id: "oyo",
    full_name: "OYO Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets-netstorage.groww.in/stocks-ipo/logos/logos-88.png",
    company: "OYO",
    date: "To be announced",
    issueSize: "₹3600 Crores",
    priceRange: "₹50-60",
    minInvest: "₹50,000",
    quantity: "100 Shares/5 Lots",
  },
  {
    id: "lic",
    full_name: "Life Insurance Corporation Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets-netstorage.groww.in/stock-assets/logos/GSTK543526.png",
    company: "LIC",
    date: "15th - 19th Nov 2022",
    issueSize: "₹21000 Crores",
    priceRange: "₹60-70",
    minInvest: "₹55,000",
    quantity: "120 Shares/6 Lots",
  },
  {
    id: "tata_power",
    full_name: "Tata Power",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets-netstorage.groww.in/stock-assets/logos/GSTK500400.png",
    company: "TATA POWER",
    date: "10th - 15th Nov 2022",
    issueSize: "₹4800 Crores",
    priceRange: "₹40-50",
    minInvest: "₹45,000",
    quantity: "110 Shares/5 Lots",
  },
  {
    id: "zomato",
    full_name: "Zomato Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets-netstorage.groww.in/stock-assets/logos/GSTK500400.png",
    company: "ZOMATO",
    date: "1st - 5th Dec 2022",
    issueSize: "₹9400 Crores",
    priceRange: "₹65-75",
    minInvest: "₹52,000",
    quantity: "130 Shares/7 Lots",
  },
  {
    id: "adani_enterprises",
    full_name: "Adani Enterprises",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets-netstorage.groww.in/stock-assets/logos/GSTK512599.png",
    company: "ADANI ENTERPRISES",
    date: "25th - 29th Nov 2022",
    issueSize: "₹9500 Crores",
    priceRange: "₹80-100",
    minInvest: "₹60,000",
    quantity: "150 Shares/8 Lots",
  },
  {
    id: "paytm",
    full_name: "One97 Communications Pvt. Ltd",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://assets.upstox.com/ipo/images/logos/paytm_logo",
    company: "One97 Communications Pvt Ltd",
    date: "12th - 16th Dec 2022",
    issueSize: "₹16600 Crores",
    priceRange: "₹85-95",
    minInvest: "₹70,000",
    quantity: "160 Shares/8 Lots",
  },
  {
    id: "phonepe",
    full_name: "PhonePe Private Limited",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis lorem libero. Aenean fermentum est et lorem pretium, sit amet scelerisque est congue. Nulla facilisi. Integer vel metus non libero varius suscipit. Fusce et sollicitudin lectus. Vivamus placerat sapien at orci dignissim venenatis.\n lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    logo: "https://www.phonepe.com/webstatic/7720/static/2a45180808d78ef097db0118995d3f7c/54610/photo.png",
    company: "PHONEPE",
    date: "22nd - 26th Dec 2022",
    issueSize: "₹6200 Crores",
    priceRange: "₹55-65",
    minInvest: "₹48,000",
    quantity: "115 Shares/6 Lots",
  },
];

export const IPO_DETAILS = {
  ipoDetails: {
    issueSize: "₹3,600 - 3,700 Cr.",
    priceRange: "₹100 - 200",
    minAmount: "₹50,000",
    issueDates: "12 Dec - 15 Dec 22",
    listedOn: "15 Dec 22",
    listedPrice: "₹150",
    lotSize: "150 shares/lots",
    listingGains: {
      value: "₹10",
      percentage: "10.0%",
    },
  },
  ipoTimeline: [
    { label: "Bidding starts", date: "12 Dec 2023" },
    { label: "Bidding ends", date: "15 Dec 2023" },
    { label: "Allotment finalization", date: "18 Dec 2023" },
    { label: "Refund initiation", date: "18 Dec 2023" },
    { label: "Demat transfer", date: "18 Dec 2023" },
    { label: "Listing date", date: "21 Dec 2023" },
  ],
};
